{
	"version": 1644960022,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"c2webappstart.js",
		"images/sayidogrusu-sheet0.png",
		"images/sayidogrusu-sheet1.png",
		"images/a1-sheet0.png",
		"images/kesir-sheet0.png",
		"images/kesir-sheet1.png",
		"images/devamspt-sheet0.png",
		"images/tiledbackground.png",
		"images/soruspt-sheet0.png",
		"images/devamspt2-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/tiledbackground3.png",
		"images/sonucspt-sheet0.png",
		"images/anasayfa-sheet0.png",
		"images/tiledbackground4.png",
		"media/dogruses (online-audio-converter.com).ogg",
		"media/yanlisses (online-audio-converter.com).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}