{
	"version": 1674427730,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/sayidogrusu-sheet0.png",
		"images/sayidogrusu-sheet1.png",
		"images/sayidogrusu-sheet2.png",
		"images/sayidogrusu-sheet3.png",
		"images/sayidogrusu-sheet4.png",
		"images/sayidogrusu-sheet5.png",
		"images/sayidogrusu-sheet6.png",
		"images/sayidogrusu-sheet7.png",
		"images/sayidogrusu-sheet8.png",
		"images/sayidogrusu-sheet9.png",
		"images/a1-sheet0.png",
		"images/kesir-sheet0.png",
		"images/kesir-sheet1.png",
		"images/devamspt-sheet0.png",
		"images/soruspt-sheet0.png",
		"images/devamspt2-sheet0.png",
		"images/tiledbackground2.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/tiledbackground3.png",
		"images/sonucspt-sheet0.png",
		"images/tiledbackground4.png",
		"images/amacbtn-sheet0.png",
		"images/amac-sheet0.png",
		"images/sprite4-sheet0.png",
		"media/dogruses (online-audio-converter.com).m4a",
		"media/dogruses (online-audio-converter.com).ogg",
		"media/yanlisses (online-audio-converter.com).m4a",
		"media/yanlisses (online-audio-converter.com).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}